[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
bytecode_hash = 'none'
remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/'
]

[fmt]
bracket_spacing = true
number_underscore = "thousands"
wrap_comments = true
line_length = 80

# See more config options https://github.com/foundry-rs/foundry/tree/master/config